name: Deploy Static Site

on:
  push:
    branches: [ gh-pages ]
    paths:
      - 'public/static/sparkofchaos.com/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        external_repository: Spark-of-Chaos/spark-of-chaos.github.io
        publish_dir: ./public/static/sparkofchaos.com
        publish_branch: gh-pages
        force_orphan: true